-- PowerShakes - Bonos de fidelización
-- Cada registro del formulario genera un código único canjeable por un helado
-- en las sedes participantes. El código se marca como "redimido" al usarse
-- y no puede volver a canjearse.

CREATE TABLE IF NOT EXISTS powershakes_bonos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo text UNIQUE NOT NULL,
  nombre text NOT NULL,
  cedula text UNIQUE NOT NULL,
  celular text NOT NULL,
  correo text,
  instagram text,
  autorizo_datos boolean NOT NULL DEFAULT false,
  estado text NOT NULL DEFAULT 'activo' CHECK (estado IN ('activo', 'redimido')),
  sede_redencion text,
  redimido_el timestamptz,
  creado_el timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_powershakes_bonos_codigo ON powershakes_bonos (codigo);

ALTER TABLE powershakes_bonos ENABLE ROW LEVEL SECURITY;

GRANT ALL PRIVILEGES ON TABLE powershakes_bonos TO postgres, service_role, anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE powershakes_bonos_id_seq TO postgres, service_role, anon, authenticated;

DROP POLICY IF EXISTS "Permitir registro publico" ON powershakes_bonos;
DROP POLICY IF EXISTS "Permitir lectura al equipo" ON powershakes_bonos;
DROP POLICY IF EXISTS "Permitir canje al equipo" ON powershakes_bonos;

-- Cualquier persona puede registrarse desde la landing (solo INSERT).
-- No puede leer ni modificar bonos existentes: así no se puede consultar
-- ni "clonar" el código de otra persona.
CREATE POLICY "Permitir registro publico"
ON powershakes_bonos FOR INSERT TO public WITH CHECK (true);

-- Solo el equipo autenticado (panel /admin) puede ver el listado y hacer seguimiento.
CREATE POLICY "Permitir lectura al equipo"
ON powershakes_bonos FOR SELECT TO authenticated USING (true);

-- Solo el equipo autenticado puede canjear (marcar como redimido) un bono.
CREATE POLICY "Permitir canje al equipo"
ON powershakes_bonos FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
